livMatS/dtool-lookup-gui

dtool_lookup_gui/Dependencies.py
dtool_lookup_gui/LookupClient.py
dtool_lookup_gui/MainApplication.py
dtool_lookup_gui/de.uni-freiburg.dtool-lookup-gui.gschema.xml
dtool_lookup_gui/dtool-lookup-gui.glade

* Reintroduces direct mongo route after plugin refactoring on server side.
* Allows configurable dependency keys for graph querying
Better not merge into master before server-side merges and releases are complete.

20201005 server side plugins

---

.gitignore
dtool_lookup_gui/MainApplication.py
dtool_lookup_gui/dtool-lookup-gui.glade

Double-click search bar to open multiline search query editor:

202111 search popover

---

dtool_lookup_gui/Dependencies.py
dtool_lookup_gui/DirectTab.py
dtool_lookup_gui/LookupTab.py
dtool_lookup_gui/MainApplication.py
dtool_lookup_gui/SettingsDialog.py
dtool_lookup_gui/TransferTab.py
dtool_lookup_gui/__init__.py
dtool_lookup_gui/__main__.py
dtool_lookup_gui/dtool-lookup-gui.glade
dtool_lookup_gui/dtool_gtk.py
dtool_lookup_gui/dtool_tk_models.py
dtool_lookup_gui/models.py
glade/README
glade/catalog/dtool_gtk_catalog.xml
requirements.txt
setup.py

Many tiny flaws, but creates, freezes, and copies. Presentable.
Metadata manipulation still missing.

2021-11-16 direct dataset manipulation and copying

---

dtool_lookup_gui/main.py
dtool_lookup_gui/models/base_uris.py
dtool_lookup_gui/models/datasets.py
dtool_lookup_gui/utils/copy_manager.py
dtool_lookup_gui/utils/logging.py
dtool_lookup_gui/utils/progressbar.py
dtool_lookup_gui/views/main_window.py
dtool_lookup_gui/views/main_window.ui
dtool_lookup_gui/widgets/base_uri_row.py
dtool_lookup_gui/widgets/progress_chart.py
dtool_lookup_gui/widgets/progress_popover_menu.py
dtool_lookup_gui/widgets/search_popover.py
dtool_lookup_gui/widgets/search_results_row.py
glade/catalog/dtool_gtk_catalog.xml

This PR implements a progress bar widget and popover to show the status of copy operations. It is based on PR #54 that implemented multiprocessing with status updates for copy operation. Addresses issue #50.

Show progress bar for copy operations

---

.github/workflows/build-and-publish.yml

publish when tagged, use workflows now embedded in master branch since https://github.com/IMTEK-Simulation/dtool-lookup-gui/pull/74

Publish when tagged

---

README.rst
dtool_lookup_gui/main.py
dtool_lookup_gui/utils/logging.py
dtool_lookup_gui/views/main_window.py
dtool_lookup_gui/views/settings_dialog.py
dtool_lookup_gui/views/settings_dialog.ui

For convenience on working with multiple dtool configurations at the same time as well as providing (partial) sample configurations to others, offer reset / import /export buttons in settings dialog.

2022-02-09 config import export

---

.github/workflows/build-and-publish.yml
CHANGELOG.md
dtool_lookup_gui/views/settings_dialog.py
dtool_lookup_gui/views/settings_dialog.ui

- Slightly modified packageing in workflows
- README.yml template file chooser in settings dialog
- User name and eMail configurable in settings dialog
- Updated changelog

2022 02 15 bits and pieces

---

.github/workflows/build-and-publish.yml
CHANGELOG.md
README.rst
setup.py

Might solve https://github.com/livMatS/dtool-lookup-gui/issues/81, impossible to test locally, needs to run here with the next release to see if working in action.

2022 02 17 disable build and publish for other than master

---

.github/workflows/build-and-publish.yml
.github/workflows/build-on-ubuntu.yml
.github/workflows/build-on-windows.yml
CHANGELOG.md
README.rst

When merged, I will push the 0.4.4 tag to make a release with MacOS binary

2022 02 21 prepare for release 0.4.4

---

.github/workflows/build-and-publish.yml

Otherwise, automatic release creation won't trigger

MAINT: inserted missing origin/master

---

dtool_lookup_gui/utils/about.py

Follow-up on https://github.com/livMatS/dtool-lookup-gui/issues/84

MAINT: Display of dtool meta package version optional

---

dtool_lookup_gui/utils/environ.py
dtool_lookup_gui/views/log_window.py
dtool_lookup_gui/views/main_window.py
pyinstaller/dtool-lookup-gui-linux-one-file.spec
pyinstaller/dtool-lookup-gui-linux.spec
pyinstaller/dtool-lookup-gui-macos-one-file.spec
pyinstaller/dtool-lookup-gui-macos.spec
pyinstaller/dtool-lookup-gui-windows-one-file.spec
pyinstaller/dtool-lookup-gui-windows.spec
pyinstaller/rthooks/pyi_rth_glib.py

Address https://github.com/livMatS/dtool-lookup-gui/issues/96

BUG: A quick attempt to address defunct 'show' button in frozen app

---

dtool_lookup_gui/models/datasets.py

Addresses https://github.com/livMatS/dtool-lookup-gui/issues/39 for any storage broker

MAINT: Catch any exception on missing readme when listing protodatasets

---

dtool_lookup_gui/views/main_window.ui

* Changed refresh icon to symbolic version
* Change down chevron to symbolic version

Some minor tweaks

---

CHANGELOG.md
dtool_lookup_gui/views/s3_configuration_dialog.py
pyinstaller/mingw64_requirements.txt
requirements.txt

exchanged DTOOL_S3_DATASET_PREFI for DTOOL_S3_DATASET_PREFIX_<BUCKET NAME>

MAINT: Bumped to dtool-s3==0.14.0,

---

dtool_lookup_gui/utils/copy_manager.py
dtool_lookup_gui/utils/multiprocessing.py

Addresses https://github.com/livMatS/dtool-lookup-gui/issues/57.

EXT: Catch errors raised by copy child process

---

dtool_lookup_gui/__init__.py
dtool_lookup_gui/de.uni-freiburg.dtool-lookup-gui.gschema.xml
dtool_lookup_gui/models/settings.py
dtool_lookup_gui/utils/subprocess.py
dtool_lookup_gui/views/main_window.py
dtool_lookup_gui/views/settings_dialog.py
dtool_lookup_gui/views/settings_dialog.ui

Addresses https://github.com/livMatS/dtool-lookup-gui/issues/173 and https://github.com/livMatS/dtool-lookup-gui/issues/174.

WIP: item download settings

---

.github/workflows/build-installer-on-windows.yml
.github/workflows/build-on-windows.yml

as described in https://github.com/livMatS/dtool-lookup-gui/issues/194

TST: Trying to fix broken windows build

---

.github/workflows/test.yml
test/conftest.py
test/test_app.py

Simple sample implementation of unit tests for GtkApplication.

2022-10-26-gui-tests

---

dtool_lookup_gui/main.py
dtool_lookup_gui/models/base_uris.py
dtool_lookup_gui/models/settings.py
dtool_lookup_gui/views/main_window.py
dtool_lookup_gui/widgets/base_uri_list_box.py

Resolves https://github.com/livMatS/dtool-lookup-gui/issues/188

duplicate local base uri fix

---

CONTRIBUTING.md
README.rst

Little changes on README and introduction of CONTRIBUTING guidelines borrowed from https://github.com/ContactEngineering/topobank/blob/main/CONTRIBUTING.md

2023 04 06 docs

---

dtool_lookup_gui/views/login_window.ui
test/test_app.py

Polishing 

---

dtool_lookup_gui/views/main_window.py

MAINT :Issue #289
